server:
  # 服务端口
  port: 8020

  tomcat:
    max-swallow-size: 600MB #修改tomcat的吞吐量

  servlet:
    context-path: /quartz


spring:
  application:
    name: quartz

  profiles:
    active: dev

  servlet:
    multipart:
      # 修改请求文件大小
      max-request-size: 400MB
      max-file-size: 200MB
      enabled: true